// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceStore.Data;

namespace ServiceStore.Migrations
{
    [DbContext(typeof(AppDBContent))]
    partial class AppDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceStore.Data.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin");

                    b.Property<string>("Age");

                    b.Property<bool>("Buy");

                    b.Property<string>("CategoryId");

                    b.Property<string>("Email");

                    b.Property<string>("LastName");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Passwrord");

                    b.Property<string>("Phone");

                    b.Property<string>("SurName");

                    b.HasKey("Id");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("ServiceStore.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId");

                    b.Property<string>("Desc");

                    b.Property<string>("FullDesc1");

                    b.Property<string>("FullDesc2");

                    b.Property<string>("FullDesc3");

                    b.Property<string>("FullDesc4");

                    b.Property<string>("FullDesc5");

                    b.Property<string>("FullDesc6");

                    b.Property<string>("FullDesc7");

                    b.Property<string>("FullDesc8");

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
